#!/bin/bash
# release.sh - Build and publish MCProxy releases
#
# Usage: ./release.sh v0.52.0
#
# This script:
#   1. Validates the version format and clean git state
#   2. Updates version in pyproject.toml files
#   3. Commits and tags the release
#   4. Builds a tarball with only release files
#   5. Generates SHA256 checksum
#   6. Uploads via gh release create

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

log_info() { echo -e "${GREEN}==>${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

#──────────────────────────────────────────────────────────────────
# VALIDATION
#──────────────────────────────────────────────────────────────────

validate_version() {
  local version="$1"

  if [[ ! "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    log_error "Invalid version format: ${version}"
    echo "  Expected: v{major}.{minor}.{patch} (e.g., v0.52.0)"
    exit 1
  fi
}

validate_clean_tree() {
  if [[ -n "$(git status --porcelain)" ]]; then
    log_error "Working tree is not clean. Commit or stash changes first."
    git status --short
    exit 1
  fi
}

validate_tools() {
  local -a required=("git" "gh" "shasum" "tar" "sed")
  for tool in "${required[@]}"; do
    if ! command -v "$tool" &>/dev/null; then
      log_error "Required tool not found: ${tool}"
      exit 1
    fi
  done
}

#──────────────────────────────────────────────────────────────────
# VERSION BUMP
#──────────────────────────────────────────────────────────────────

bump_version() {
  local version="$1"
  local bare_version="${version#v}"  # Strip 'v' prefix

  log_info "Bumping version to ${version}..."

  # Update pyproject.toml
  sed -i '' "s/^version = \".*\"/version = \"${bare_version}\"/" \
    "${SCRIPT_DIR}/pyproject.toml"

  # Update ble_service/pyproject.toml
  sed -i '' "s/^version = \".*\"/version = \"${bare_version}\"/" \
    "${SCRIPT_DIR}/ble_service/pyproject.toml"

  log_info "  Updated pyproject.toml files"
}

#──────────────────────────────────────────────────────────────────
# TARBALL BUILD
#──────────────────────────────────────────────────────────────────

build_tarball() {
  local version="$1"
  local tarball_name="mcproxy-${version}.tar.gz"
  local prefix="mcproxy-${version}"
  local tmp_dir
  tmp_dir=$(mktemp -d)
  local staging="${tmp_dir}/${prefix}"

  log_info "Building release tarball..."

  mkdir -p "$staging"

  # Copy included files
  cp "${SCRIPT_DIR}/pyproject.toml" "$staging/"
  cp "${SCRIPT_DIR}/uv.lock" "$staging/" 2>/dev/null || log_warn "  No uv.lock found (will be generated by uv sync)"
  cp "${SCRIPT_DIR}/config.sample.json" "$staging/" 2>/dev/null || true

  # src/mcproxy/ package
  mkdir -p "${staging}/src/mcproxy/commands"
  find "${SCRIPT_DIR}/src/mcproxy" -name '*.py' -not -path '*/__pycache__/*' | while read -r f; do
    local rel="${f#${SCRIPT_DIR}/}"
    mkdir -p "${staging}/$(dirname "$rel")"
    cp "$f" "${staging}/${rel}"
  done

  # ble_service/
  mkdir -p "${staging}/ble_service/src"
  cp "${SCRIPT_DIR}/ble_service/pyproject.toml" "${staging}/ble_service/"
  find "${SCRIPT_DIR}/ble_service/src" -name '*.py' -not -path '*/__pycache__/*' | while read -r f; do
    local rel="${f#${SCRIPT_DIR}/}"
    mkdir -p "${staging}/$(dirname "$rel")"
    cp "$f" "${staging}/${rel}"
  done

  # bootstrap/ directory
  cp -r "${SCRIPT_DIR}/bootstrap" "${staging}/bootstrap"
  # Remove any generated files from bootstrap copy
  find "${staging}/bootstrap" -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true

  # Build tarball
  tar -czf "${SCRIPT_DIR}/${tarball_name}" -C "$tmp_dir" "$prefix"

  # Cleanup staging
  rm -rf "$tmp_dir"

  log_info "  Built ${tarball_name}"
  echo "$tarball_name"
}

generate_checksum() {
  local tarball="$1"
  local checksum_file="${tarball}.sha256"

  log_info "Generating SHA256 checksum..."

  (cd "${SCRIPT_DIR}" && shasum -a 256 "$tarball" > "$checksum_file")

  log_info "  $(cat "${SCRIPT_DIR}/${checksum_file}")"
  echo "$checksum_file"
}

#──────────────────────────────────────────────────────────────────
# GIT + GITHUB RELEASE
#──────────────────────────────────────────────────────────────────

commit_and_tag() {
  local version="$1"

  log_info "Creating git commit and tag..."

  git -C "$SCRIPT_DIR" add pyproject.toml ble_service/pyproject.toml
  git -C "$SCRIPT_DIR" commit -m "[chore] Bump version to ${version}"
  git -C "$SCRIPT_DIR" tag -a "$version" -m "Release ${version}"

  log_info "  Committed and tagged ${version}"
}

upload_release() {
  local version="$1"
  local tarball="$2"
  local checksum="$3"

  log_info "Creating GitHub release ${version}..."

  local -a assets=("${SCRIPT_DIR}/${tarball}" "${SCRIPT_DIR}/${checksum}")

  gh release create "$version" \
    --title "MCProxy ${version}" \
    --notes "Release ${version}" \
    --draft \
    "${assets[@]}"

  log_info "  Draft release created: ${version}"
  log_info "  Review and publish at: https://github.com/DK5EN/McAdvChat/releases"
}

#──────────────────────────────────────────────────────────────────
# CLEANUP
#──────────────────────────────────────────────────────────────────

cleanup_artifacts() {
  local tarball="$1"
  local checksum="$2"

  rm -f "${SCRIPT_DIR}/${tarball}" "${SCRIPT_DIR}/${checksum}"
  log_info "  Cleaned up local artifacts"
}

#──────────────────────────────────────────────────────────────────
# MAIN
#──────────────────────────────────────────────────────────────────

main() {
  if [[ $# -lt 1 ]]; then
    echo "Usage: ./release.sh v{major}.{minor}.{patch}"
    echo "  Example: ./release.sh v0.52.0"
    exit 1
  fi

  local version="$1"

  echo ""
  echo "  MCProxy Release Builder"
  echo "  ========================"
  echo ""

  validate_version "$version"
  validate_tools
  validate_clean_tree

  log_info "Preparing release ${version}..."
  echo ""

  # Step 1: Bump version
  bump_version "$version"

  # Step 2: Commit and tag
  commit_and_tag "$version"

  # Step 3: Build tarball
  local tarball
  tarball=$(build_tarball "$version")

  # Step 4: Generate checksum
  local checksum
  checksum=$(generate_checksum "$tarball")

  # Step 5: Upload to GitHub
  upload_release "$version" "$tarball" "$checksum"

  # Step 6: Cleanup local artifacts
  cleanup_artifacts "$tarball" "$checksum"

  echo ""
  log_info "Release ${version} created successfully!"
  echo ""
  echo "  Next steps:"
  echo "  1. Review the draft release on GitHub"
  echo "  2. Edit release notes if needed"
  echo "  3. Publish the release"
  echo "  4. Push the tag: git push origin ${version}"
  echo "  5. Push the commit: git push"
  echo ""
}

main "$@"
